name: Build ISO
on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      - name: Install live-build
        run: |
          sudo apt update
          sudo apt-get install live-build
      - name: Build
        run: |
          sudo lb build

