name: Build ISO
on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install live-build
        run: |
          apt-get update
          apt-get -y install debootstrap debhelper live-build sudo
      - name: Build
        run: |
          sudo lb build

