name: Build ISO
on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install live-build
        run: |
          sudo apt-get update
          sudo apt-get -y install coreutils debootstrap debhelper live-build
      - name: Build
        run: |
          sudo lb build

