name: Build ISO
on: push

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install live-build
        run: |
          git clone https://salsa.debian.org/live-team/live-build.git
          cd live-build
          make install
      - name: Build
        run: |
          sudo lb build

